- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest

- name: Install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - packages
